### PR TITLE
Config timeout

### PR DESCRIPTION
**Pull request by jshumaker-accusoft**
Allows configuring the timeout for requests to some value besides the default 2 seconds.

### CODE REVIEW

**Review by peter-murray — COMMENTED** [review]
I would tend to using an || instead of a ternary in these scenarios

**Comment by jshumaker-accusoft** [comment]
I considered using that, but wasn't sure if Axios would accept 0 as a timeout value that disables timeouts or not and || instead of ternary would not allow for 0.

**Comment by peter-murray** [comment]
I don't view 0 as a valid timeout value in this context... otherwise you can make the library block and then you get issues raised on the library

**Comment by jshumaker-accusoft** [comment]
Seems fine to me. I have no intention of using a timeout of 0 myself and can see how it could cause issues.

**Pull request merged**
